name: scilenzio-yeast-nf
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - git
  - python>=3.8
  - docopt
  - bioconda::fastp
  - bioconda::star=2.7.0
  - bioconda::samtools
  - bioconda::bcftools
  - bioconda::bedtools
  - bioconda::salmon
  - bioconda::seqkit
  - bioconda::gffread
  - bioconda::subread
  # - conda-forge::r-base>=4.3.1
  # - conda-forge::r-tidyverse
  # - conda-forge::r-rlang>=1.1.0
  # - conda-forge::r-dplyr
  # - conda-forge::r-docopt
  # - conda-forge::r-cowplot
  # - conda-forge::r-paletteer
  # - conda-forge::r-ggrepel
  # - conda-forge::gsl # needed to install bcftools correctly
  # - bioconda::bioconductor-tximport
  # - bioconda::bioconductor-genomicfeatures
  # - bioconda::bioconductor-deseq2
  # - bioconda::bioconductor-rtracklayer